// Copyright FreeboozStudio. All Rights Reserved.

#include "Common/DBALogChannels.h"

DEFINE_LOG_CATEGORY(LogDBACore);
DEFINE_LOG_CATEGORY(LogDBAFrontend);
DEFINE_LOG_CATEGORY(LogDBAMatch);
DEFINE_LOG_CATEGORY(LogDBACombat);
DEFINE_LOG_CATEGORY(LogDBAUI);
DEFINE_LOG_CATEGORY(LogDBAData);
DEFINE_LOG_CATEGORY(LogDBANetwork);
DEFINE_LOG_CATEGORY(LogDBAValidation);
DEFINE_LOG_CATEGORY(LogDBAAI);
DEFINE_LOG_CATEGORY(LogDBATelemetry);
DEFINE_LOG_CATEGORY(LogDBAGameOps);