server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          __path__: /var/log/**/*.log

  - job_name: game-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: game-api
          __path__: /app/logs/*.json

  - job_name: game-worker
    static_configs:
      - targets:
          - localhost
        labels:
          job: game-worker
          __path__: /app/logs/*.json